# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f5c9c1d3d27136db97689e2713de64b3788b67829ae568663a2c9bd9126c9a83c16104aabe02bffde52312612a2118d4d16f3dc9f8f8a73e6fe5ccb9dcdf92

test:
  secret_key_base: 260bf1f854ef94292b328817edbb190880989792fa982821a3e91ee286462f2b597d9b5590bd68c1b7b1c79c98bdf09961dea9a5be3547bb8dd7a8942090a7ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
